### ISSUE TITLE
Migrate Staging

### ISSUE THREAD

**Issue by sslaws** [bcgov/SIMS#3126]
** User Story **
As a project team, we want to isolate our environments to reduce single OCP project quota and to make the deployment process more manageable.

**Acceptance Criteria:**
- [x]  Move After 1.7 Release to Staging Environment 
- [x]  Move Staging from 0c27fb-test project to a6ef19-test
- [x] Staging deployment artifacts should no longer be present in 0c27fb-test
- [x] Update staging deployment GH action to deploy to the new staging
- [x] Update current GitHub staging configs
  - [x] Update configuration to disable Fulltime
  - [x] update configuration to enable study period overlap validation

**Technical**
- [X] Investigate if the same service account used by GitHub actions can have access to deploy to the new project `a6ef19-test` (this is the preferred way and it seems to be feasible).
- [x] If not possible to to reuse the same service account do research on how to allow the images generated from the current tool namespace into the new `0c27fb-test`.
- [x] Once the service account has permission execute the steps to create a new environment from scratch. Follow as best as possible the instructions in the [wiki](https://github.com/bcgov/SIMS/wiki/DevOps-and-Running-the-Application#openshift-infrastructure) and adjust any missing step.

For the first AC, a Rolebinding has to be created in each namespace to give access to the service account in the 0c27fb tools namespace.  After reviewing the SAs, I added RBs for github-action which looked like the correct one.

```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: github-action
  namespace: a6ef19-tools
subjects:
  - kind: ServiceAccount
    name: github-action
    namespace: 0c27fb-tools
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
```
I subsequently validated access

```console
 You have access to the following projects and can switch between them with ' project <projectname>':
  * 0c27fb-dev - Student Information Management System (dev)
    0c27fb-prod - Student Information Management System (prod)
    0c27fb-test - Student Information Management System (test)
    0c27fb-tools - Student Information Management System (tools)
    a6ef19-dev - SIMS Staging (dev)
    a6ef19-prod - SIMS Staging (prod)
    a6ef19-test - SIMS Staging (test)
    a6ef19-tools - SIMS Staging (tools)
```
