### ISSUE TITLE
SDPR API - Response Schema Update

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#4281]
**User Story**
As a system, SIMS needs to provide more data for SDPR ISA for them to be able to implement their interface policy. Interface policy exists for SDPR to review students who are receiving assistance towards living costs and validate if they are also receiving living expenses funding from SABC financial aid.

**Acceptance Criteria**
- [x] Student details should be shown even if there is NO eligible application data to share.

- [x] Successful SIN Match Outcomes:
    - [x] SFAS Only: Send student details from `sfas_individuals` and any applications within the timeframe.
    - [x] SIMS Only: Send student details **IF** the current SIN has been validated, otherwise no match.
    - [x] SFAS & SIMS: Send student details from SIMS **IF** the current SIN has been validated, otherwise send `sfas_individuals`
---
- [x] Update incoming field in the bridge file from "Assessed costs-discretionary" into "Eligible need". Same position and length.

---
- [x] Applications to include on successful matches:
    - [x] Include only applications that are FT, AND
    - [x] Within the current program year PLUS 2 previous program years
        - If request is September 1, 2024: include current PY (24/25) and two prev (22/23 and 23/24)
        - If request is June 1, 2024: include current PY (23/24) and two prev (21/22 and 22/23)
    - [x] Show all SFAS applications that meet the above 
    - [x] Show all SIMS applications that meet the above AND:
        - [x] Application is not Overwritten, Draft, or In progress.
        - [x] Use most current assessment completed.

- [x] Institution information will always be pulled from matching SIMS institution code. If nothing found, just include institution code, everything else institution based can be empty/null. 

---
- [x] Update Schema to include more items:
```
student:
    givenNames 
    lastName
    sin
    dateOfBirth
    phoneNumber
    address:
        addressline1
        addressline2
        city
        prov
        postal
        country
applications:
    appNumber: applications.application_number
    appStatus:
    cancelDate: 
    withdrawDate: // dateOfWithdrawal 
    withdrawReason: //include "Student withdrew from program" events
    withdrawActive: //SFAS only for now until SIMS builds it
    immigrationStatus: applications.data{citizenship}
    bcResidency:
    legacyPermanentResident:
    maritalStatus: 
    legacyMaritalDate:  //only include if SFAS application data, 
    income: applications.data{taxReturnIncome}
    livingArrangement: (home/away)
    estimatedTotalAward: //sum of all disbursement amts from app without Total BC Grants similar to NOA
    dependants:
        fullName:
        dateOfBirth:
    program:
        length: education_programs_offerings.study_breaks{"totalFundedWeeks"}
        startDate: education_programs_offerings.study_start_date
        endDate: education_programs_offerings.study_end_date
        courseLoad: "FT" // sfas has more course load options
    institution:
        locationCode: 
        locationName: institution_locations.name
        primaryContact: institution_locations.primary_contact (first/last)
        email: institution_locations.primary_contact (email)
        phone: institution_locations.primary_contact (phone)
    costs:
        tuition: calculatedDataTotalTutionCost / tuition from sfas
        booksAndSupplies: calculatedDataTotalBookCost / books from sfas
        exceptionalExpenses: offeringExceptionalExpenses / exceptional from sfas
        livingAllowance: // calculatedDataTotalMSOLAllowance / living allowance from sfas
        secondResidence: // SFAS: extra shelter & SIMS: calculatedDataTotalSecondResidence
        childCare: calculatedDataTotalChildCareCost
        alimony: calculatedDataTotalChildSpousalSupport
        totalTransportation: // calculatedDataTotalTransportationCost
        totalNeed: // calculatedDataProvincialAssessedNeed / total provincial need (use space from discretionary it will maybe need to be renamed)
    disbursements:
        awardCode:
        amount: //use effective amount if ecert sent or estimated if not
        fundingDate: // earliest disb date
        requestDate: // issue date sfas / ecert send date sims
```

**Business Context**
Current Schema:
<img width="800" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODJQQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bb7a4f51cb60243212001c2ec60923a6cacb7f25/image.png" alt="image.png" />

**Technical Analysis**

Student search possible outcomes:
Logic: Search in both SIMS and SFAS based on SIN(current valid SIN in SIMS)
 - Student found only in SIMS
 - Student found only in SFAS
 - Student found in both SIMS and SFAS
 - Student not found in both SIMS and SFAS
 
Based on the outcomes above, the application search will be done as follows
> Student found only in SIMS
>> Get Student Details from SIMS
>> Search Applications only in SIMS

> Student found only in SFAS
 >> Get Student Details from SFAS
 >> Search Applications only in SFAS

> Student found in both SIMS and SFAS
 >> Get Student Details from SFAS
 >>  Search Applications on both SIMS and SFAS

> Student not found in both SIMS and SFAS
 >> no application search required.

> Select the PY to get application data based on PY id
```sql
     SELECT
	PY.PROGRAM_YEAR,
	PY.ID
	FROM
		SIMS.PROGRAM_YEARS PY
	WHERE
		PY.START_DATE <= (
			SELECT
				INNER_PY.START_DATE
			FROM
				SIMS.PROGRAM_YEARS INNER_PY
			WHERE
				NOW() BETWEEN INNER_PY.START_DATE AND INNER_PY.END_DATE
		)
	ORDER BY PY.start_date DESC

	LIMIT 3;
```

> Select the PY to get application data based on min and max `study_start_date`
```sql
SELECT
	MIN(PY.START_DATE) min_start_date,
	MAX(PY.START_DATE) max_start_date
FROM
	SIMS.PROGRAM_YEARS PY
WHERE
	PY.START_DATE <= (
		SELECT
			INNER_PY.START_DATE
		FROM
			SIMS.PROGRAM_YEARS INNER_PY
		WHERE
			NOW() BETWEEN INNER_PY.START_DATE AND INNER_PY.END_DATE
	);
```

---

**Technical**

- [x] From SIMS consider only FT applications which has it's current assessment calculation is completed (assessment_status: Completed).
- [ ] Get applications from SIMS and SFAS(based on student existing in the system) which are from current PY + past 2 PYs.
   - [ ] Get the `min` and `max` study_start_date which falls under current PY + past 2 PYs.
   - [ ] Get SIMS applications which has start_date between `min` and `max` days.
   - [ ] Get SFAS appplications which has start_date between `min` and `max` days.
   
- [x] Get institution details only from SIMS. If the application data is from SFAS, use the institution code(institution location code) to match SIMS data and pull institution details.
- [x] For both student and application data, add a property `isLegacy` to specify the source of data.

- [x]  E2E Tests
 - SIMS Student and application data
 - SFAS Student and application data
 - Both SIMS and SFAS data.
 - Institution code missing in SIMS.
