### ISSUE TITLE
Preparation for Upgrade PostgreSQL from version 15 to 17

### ISSUE THREAD

**Issue by sh16011993** [bcgov/SIMS#4782]
**Description**

We need to upgrade our PostgreSQL cluster from version 15 to version 17 to benefit from the latest features, performance improvements, and security fixes.

**Current State**

- PostgreSQL version: 15
- Crunchy Postgres Operator version: v5.0.4 for managing the cluster

### **Acceptance Criteria**

- [ ] Use the alternative DEV environment at `a6ef19-dev` to install a fresh Crunchy with Postgres 15 to allow the test upgrades. Once we are confident, we can finally apply the solution to DEV in a similar way to how it will be implemented during the releases.
- [ ] Follow the steps below to upgrade Postgres to the latest version.
- [ ] Ensure that the backup and restore process from step 1 is validated in DEV environment. Take a backup, create a resource immediately afterwards and then do the restore using the created backup. Verify that the database is restored successfully to the state immediately before the resource creation.
- [ ] Use the backup instructions in the [SIMS Wiki](https://github.com/bcgov/SIMS/wiki/DevOps-and-Running-the-Application#crunchy-backup-and-restore) and validate if any additional backup is required. If required, check [Crunchy docs](https://access.crunchydata.com/documentation/postgres-operator/5.7/tutorials/backups-disaster-recovery/backup-management#taking-a-one-off-backup.).
- [ ] By the end of this effort, the DEV environment is expected
  - [ ] To be upgraded to the latest Postgres available version (17.5)
  - [ ] Backup and restore documentation updated in the Wiki, if required.
  - [ ] Documentation of the Postgres upgrade to be executed this time and next times, in the Wiki and in the release instructions.
  - [ ] Walkthrough of the process to the Team along the sprint.

**Note:** Before proceeding with the Postgres upgrade, ensure that the Postgres Operator is upgraded to a version compatible with the Postgres version. (Reference link for version compatibility: https://access.crunchydata.com/documentation/postgres-operator/latest/references/components

Reference Link for the below mentioned steps: https://access.crunchydata.com/documentation/postgres-operator/5.7/guides/major-postgres-version-upgrade

### **Steps to follow for the upgrade:** 

1) Take a full one-off backup of the database. Follow the steps here to take this backup: https://access.crunchydata.com/documentation/postgres-operator/5.7/tutorials/backups-disaster-recovery/backup-management#taking-a-one-off-backup. 

Modify (add the following sections) in the `crunchy-db.yml` as below to enable the functionality of taking a `one-off backup` and being able to restore from it during the `crunchy db` upgrade process.

Add/modify the following `inputs` to the `workflow_dispatch`:

```
on:
  workflow_dispatch:
    inputs:
      take_backup:
        description: "Take a one-off backup before proceeding"
        required: false
        type: boolean
        default: false
      restore_type:
        description: "Restore type"
        required: false
        type: choice
        options:
          - time-based
          - backup-name
        default: "time-based"
      restore_target:
        description: "Restore target date and time in 'YYYY-MM-DD HH:MM:SS' format (for time-based restore)"
        required: false
        type: string
        default: ""
      backup_name:
        description: "Name of backup to restore from (for backup-name restore)"
        required: false
        type: string
        default: ""
```

Add the following step after the `Log in to OpenShift` step:

```
- name: Take One-Off Backup
        if: ${{ inputs.take_backup }}
        id: backup
        run: |
          echo "Taking a one-off backup before proceeding..."
          
          # Create a unique backup name with timestamp
          BACKUP_NAME="${{ env.CLUSTER_NAME }}-pre-$(date +%Y%m%d-%H%M%S)"
          echo "backup_name=${BACKUP_NAME}" >> $GITHUB_OUTPUT
          
          # Create the custom resource for a one-off backup
          cat <<EOF | kubectl apply -n ${{ secrets.OPENSHIFT_ENV_NAMESPACE }} -f -
          apiVersion: postgres-operator.crunchydata.com/v1beta1
          kind: PGBackRest
          metadata:
            name: ${BACKUP_NAME}
          spec:
            pgbackrest:
              selector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: ${{ env.CLUSTER_NAME }}
              manual:
                repoName: repo1
                options:
                  - "--type=full"
          EOF
          
          echo "One-off backup initiated with name: ${BACKUP_NAME}"
          echo "Waiting for backup to complete..."
          
          # Wait for backup to start (give it 30 seconds)
          sleep 30
          
          # Monitor backup status - wait up to 10 minutes for completion
          MAX_ATTEMPTS=60
          ATTEMPT=0
          COMPLETED=false
          
          while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
            STATUS=$(kubectl get pgbackrest -n ${{ secrets.OPENSHIFT_ENV_NAMESPACE }} ${BACKUP_NAME} -o jsonpath='{.status.conditions[?(@.type=="PGBackRestBackupComplete")].status}' 2>/dev/null)
            
            if [ "$STATUS" == "True" ]; then
              echo "Backup completed successfully."
              COMPLETED=true
              break
            fi
            
            echo "Backup still in progress. Checking again in 10 seconds..."
            sleep 10
            ATTEMPT=$((ATTEMPT+1))
          done
          
          if [ "$COMPLETED" != "true" ]; then
            echo "Warning: Backup did not complete within the timeout period. Continuing with caution."
          fi
```

Modify the `Validate Date Time Format` step as following:

```      
      # Validate inputs for restore based on the restore type
      - name: Validate Restore Inputs
        if: ${{ inputs.action == 'upgrade' && inputs.restore_enabled }}
        run: |
          if [ "${{ inputs.restore_type }}" == "time-based" ]; then
            # Define the date-time format regex pattern
            DATE_TIME_REGEX='^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$'
            if ! echo "${{ inputs.restore_target }}" | grep -Pq "$DATE_TIME_REGEX"; then
              echo "Error: RESTORE_TARGET must be in the format 'YYYY-MM-DD HH:MM:SS' for time-based restore."
              exit 1
            fi
            echo "Using time-based restore to point-in-time: ${{ inputs.restore_target }}"
          elif [ "${{ inputs.restore_type }}" == "backup-name" ]; then
            if [ -z "${{ inputs.backup_name }}" ]; then
              echo "Error: backup_name must be provided for backup-name restore type."
              exit 1
            fi
            echo "Using backup-name restore from backup: ${{ inputs.backup_name }}"
          fi
```
 
Modify the following step to ensure the `Makefile` is called correctly:
```
      - name: Manage Crunchy DB
        working-directory: "./devops/helm/crunchy-postgres/"
        run: |
          if [ "${{ inputs.action }}" == "install" ]; then
            make install NAMESPACE=${{ secrets.OPENSHIFT_ENV_NAMESPACE }}
          elif [ "${{ inputs.action }}" == "upgrade" ]; then
            if [ "${{ inputs.restore_enabled }}" == "true" ]; then
              if [ "${{ inputs.restore_type }}" == "time-based" ]; then
                make upgrade NAMESPACE=${{ secrets.OPENSHIFT_ENV_NAMESPACE }} RESTORE_ENABLED=true RESTORE_TYPE=time RESTORE_TARGET="${{ inputs.restore_target }}"
              elif [ "${{ inputs.restore_type }}" == "backup-name" ]; then
                BACKUP_TO_RESTORE="${{ inputs.backup_name }}"
                # If we just took a backup and no explicit backup name was provided, use the one we just created
                if [ "${{ inputs.take_backup }}" == "true" ] && [ -z "${{ inputs.backup_name }}" ]; then
                  BACKUP_TO_RESTORE="${{ steps.backup.outputs.backup_name }}"
                  echo "Using the backup we just created: ${BACKUP_TO_RESTORE}"
                fi
                make upgrade NAMESPACE=${{ secrets.OPENSHIFT_ENV_NAMESPACE }} RESTORE_ENABLED=true RESTORE_TYPE=name BACKUP_NAME="${BACKUP_TO_RESTORE}"
              fi
            else
              make upgrade NAMESPACE=${{ secrets.OPENSHIFT_ENV_NAMESPACE }}
            fi
          fi
```

`Makefile` update in `crunchy-postgres` to support the newly added `RESTORE_TYPE` and `BACKUP_NAME` parameters for the restore operation.

```
.PHONY: upgrade
upgrade: helm-dep
    @if [ "${RESTORE_ENABLED}" = "true" ]; then \
        if [ "${RESTORE_TYPE}" = "time-based" ]; then \
            if [ -z "${RESTORE_TARGET}" ]; then \
                echo "Error: RESTORE_TARGET is required when RESTORE_TYPE is time-based."; \
                exit 1; \
            fi; \
            helm upgrade --install $(call arguments) --set restore.enabled=${RESTORE_ENABLED} --set restore.options.target="${RESTORE_TARGET}"; \
        elif [ "${RESTORE_TYPE}" = "backup-name" ]; then \
            if [ -z "${BACKUP_NAME}" ]; then \
                echo "Error: BACKUP_NAME is required when RESTORE_TYPE is backup-name."; \
                exit 1; \
            fi; \
            helm upgrade --install $(call arguments) --set restore.enabled=${RESTORE_ENABLED} --set restore.backupName="${BACKUP_NAME}"; \
        else \
            echo "Error: RESTORE_TYPE must be either 'time-based' or 'backup-name'."; \
            exit 1; \
        fi; \
    else \
        helm upgrade --install $(call arguments) --set restore.enabled=false; \
    fi
```

2) Create a new PG Upgrade custom resource file:

```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PGUpgrade
metadata:
  name: {{ template "crunchy-postgres.fullname" . }}-upgrade-to-17
  labels:
    {{ include "crunchy-postgres.labels" . | nindent 4 }}
spec:
  fromPostgresCluster:
    name: {{ template "crunchy-postgres.fullname" . }}
    namespace: {{ .Release.Namespace }}
  toPostgresCluster:
    name: {{ template "crunchy-postgres.fullname" . }}-v17
    namespace: {{ .Release.Namespace }}
  postgresVersion: 17
```

3) Update the `values.yaml` file to specify PostgreSQL version 17 for the upgrade.

4) Since the Crunchy Data Postgres Operator does not explicitly shutdown and annotate the cluster before initializing the upgrade. This needs to be created as a job for the PGO to work on. The pre-upgrade job with the annotation ensures the PostgreSQL cluster is properly shut down first before initializing the upgrade.
Annotations file for shutdown:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "crunchy-postgres.fullname" . }}-shutdown-annotation
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.serviceAccountName | default "default" }}
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          kubectl annotate --overwrite postgrescluster {{ template "crunchy-postgres.fullname" . }} -n {{ .Release.Namespace }} postgres-operator.crunchydata.com/shutdown="true"
      restartPolicy: OnFailure
  backoffLimit: 4
```

5) Below job needs to run as a post-upgrade job to perform the annotations cleanup
```
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "crunchy-postgres.fullname" . }}-post-upgrade-cleanup
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.serviceAccountName | default "default" }}
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          # Remove the shutdown annotation if it exists
          kubectl annotate postgrescluster {{ template "crunchy-postgres.fullname" . }}-v17 -n {{ .Release.Namespace }} postgres-operator.crunchydata.com/shutdown-
      restartPolicy: OnFailure
  backoffLimit: 4
```

6) Wait and watch step: When the last Postgres Pod is terminated, the PGO-Upgrade process will kick into action, upgrading the primary database and preparing the replicas. On watching the namespace, one will see the PGUpgrade controller start Pods for each of those actions. To keep track of the process and see when it finishes, one can look at the `status.conditions` field of the PGUpgrade object. If the upgrade process encounters any blockers preventing it from finishing, the `status.conditions` field will report on those blockers. When it finishes upgrading the cluster, it will show the status conditions:
```
type: "Progressing"
status: "false"
reason: "PGUpgradeCompleted"
```

```
type:   "Succeeded" status: "true"
reason: "PGUpgradeSucceeded"
```

7) Once the upgrade process completes, restart the postgres cluster with the new version.
